Added some metadata properties
wcde-studio/ls-frontend pull request #19
Opened 2024-04-16 10:10 UTC by VanoVasilyan

Added some metadata properties

2024-04-16 10:16 UTC, Gyxer513 requested changes

2024-04-16 10:16 UTC, Gyxer513 commented on src/app/layout.tsx
>  	description: 'Generated by create next app',
Запроси описание у Виталия, пожалуйста. 
@dwatheone

2024-05-04 19:52 UTC, VanoVasilyan commented on src/app/layout.tsx
>  	description: 'Generated by create next app',
Поменял

2024-05-13 09:56 UTC, Gyxer513 requested changes
Не нужно вносить изменения в файлы проекта, не относящиеся к задаче, добавленные мета данные приняты, остальное нужно убрать. Если есть предложения или замечания по коду, лучше сначала их обсудить до начала работы.

2024-07-04 10:34 UTC, Gyxer513 requested changes
В ветви замечены конфликты, необходимо сделать силяние с основной, при этом убрать все лишнее.

2024-07-05 12:58 UTC, Gyxer513 approved these changes
Изменения приняты.

2024-07-05 12:58 UTC, merged